name: 'Hotfix Production to Master'
description: 'To cherrypick the hotfix commit merged to Production and create a PR to the master branch'
inputs:
  commit-id-for-picking:  # id of input
    description: 'The merge commit of the hotfix'
    required: true
    default: 'World'
outputs:
  pr-link: # id of output
    description: 'Outputs the commit hash of the cherrypicked commit'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commit-id-for-picking }}

# inputs:
#   mergeCommit:
#     description: 'The merge commit of the hotfix'
#     required: true
#   outputs:
#     commitHash:
#       description: 'Outputs the commit hash of the cherrypicked commit'
#   runs:
#     using: 'docker'
#     image: 'Dockerfile'
#     args:
#       - ${{ inputs.mergeCommit }}
