# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Production ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Hotfix from Production to Master
      id: hotfix-master
      uses: https://github.com/pragatheeswarans/hotfix-production-master-action/hotfix-production-master-action@v1.0
      with:
        merge-commit: ${{ github.sha }}
    - name: 'Output the commit-sha'
      run: echo "The output was ${{ steps.hotfix-master.outputs.commit-hash }}"
